# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170304_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='character',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='lineId',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
