# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170705_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='lineId',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
